server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/v1/medicos {
    proxy_pass http://backend-php:8000/api/v1/medicos;
    proxy_set_header Host $host;
  }

  location /api/v1/pacientes {
    proxy_pass http://backend-node:3000/api/v1/pacientes;
    proxy_set_header Host $host;
  }
}